IMS.web/Controllers/DashboardController.cs
using IMS.infrastructure.IRepository;
using IMS.models.Entity;
using IMS.models.ViewModels;
using IMS.web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace IMS.web.Controllers
{
    [Authorize(Roles = "ADMIN,COUNTER,STORE")]
    public class DashboardController : Controller
    {
        private readonly ICrudService<SupplierInfo> _supplierInfo;
        private readonly ICrudService<CustomerInfo> _customerInfo;
        private readonly ICrudService<CategoryInfo> _categoryInfo;
        private readonly ICrudService<ProductInfo> _productInfo;
        private readonly IRawSqlRepository _rawSqlRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICrudService<StockInfo> _stockInfo;

        public DashboardController(ICrudService<SupplierInfo> supplierInfo,
           ICrudService<CustomerInfo> customerInfo,
           ICrudService<CategoryInfo> categoryInfo,
           ICrudService<ProductInfo> productInfo,
           IRawSqlRepository rawSqlRepository,
           UserManager<ApplicationUser> userManager,
           ICrudService<StockInfo> stockInfo)


        {
            _supplierInfo = supplierInfo;
            _customerInfo = customerInfo;
            _categoryInfo = categoryInfo;
            _productInfo = productInfo;
            _rawSqlRepository = rawSqlRepository;
            _userManager = userManager;
            _stockInfo = stockInfo;
        }
        public async Task<IActionResult> Index()
        {
            DashboardViewModel dashboardViewModel = new DashboardViewModel();
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId);

            ViewBag.CategoryInfos = await _categoryInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);
            ViewBag.ProductInfos = await _productInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);

            dashboardViewModel.StockInfos = await _stockInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId && p.Quantity <= 10);

            var result = _rawSqlRepository.FromSql<DashboardList>(
               "usp_getDashboardList @storeId",
               new SqlParameter("@storeId", user.StoreId)
           ).ToList();

            dashboardViewModel.DashboardListInfos = result;


            var results = _rawSqlRepository.FromSql<DashboardIndex>(
              "usp_getDashboardIndex @storeId",
              new SqlParameter("@storeId", user.StoreId)
          ).ToList();
            dashboardViewModel.DashboardIndex = results.FirstOrDefault() ?? new DashboardIndex();
            return View(dashboardViewModel);
        }
    }
}

IMS.web/Controllers/RackInfoController.cs
using IMS.infrastructure.IRepository;
using IMS.models.Entity;
using IMS.web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IMS.web.Controllers
{
    public class RackInfoController : Controller
    {
        private readonly ICrudService<RackInfo> _rackInfo;
        private readonly UserManager<ApplicationUser> _userManager;
        public RackInfoController(ICrudService<RackInfo> rackInfo, UserManager<ApplicationUser> userManager)
        {
            _rackInfo = rackInfo;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId);
            var rackInfo = await _rackInfo.GetAllAsync(e => e.StoreInfoId == user.StoreId);
            return View(rackInfo);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            RackInfo rackInfo = new RackInfo();
            rackInfo.IsActive = true;
            if (id > 0)
            {
                rackInfo = await _rackInfo.GetAsync(id);
            }
            return View(rackInfo);
        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(RackInfo rackInfo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userId = _userManager.GetUserId(HttpContext.User);
                    var user = await _userManager.FindByIdAsync(userId);
                    if (rackInfo.Id == 0)
                    {
                        rackInfo.CreatedDate = DateTime.Now;
                        rackInfo.CreatedBy = userId;
                        rackInfo.StoreInfoId = user.StoreId;
                        await _rackInfo.InsertAsync(rackInfo);
                        TempData["Success"] = "Rack Info Added Successfully";
                    }
                    else
                    {
                        var OrgRackInfo = await _rackInfo.GetAsync(rackInfo.Id);
                        OrgRackInfo.RackName = rackInfo.RackName;
                        OrgRackInfo.IsActive = rackInfo.IsActive;
                        OrgRackInfo.ModifiedDate = DateTime.Now;
                        await _rackInfo.UpdateAsync(OrgRackInfo);
                        TempData["Success"] = "Rack Info Updated Successfully";
                    }
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception )
                {
                    TempData["Error"] = "Error Occured While Adding/Updating Unit Info";
                    return RedirectToAction(nameof(AddEdit));
                }
            }
            TempData["Error"] = "Please Enter Valid Data";
            return RedirectToAction(nameof(AddEdit));
        }
    }
}

IMS.web/Controllers/ReportController.cs
using IMS.infrastructure.IRepository;
using IMS.models.Entity;
using IMS.models.ViewModels;
using IMS.web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using System.Data;

namespace IMS.web.Controllers
{
    public class ReportController : Controller
    {
        public readonly UserManager<ApplicationUser> _userManager;
        public readonly ICrudService<SupplierInfo> _supplierInfo;
        public readonly ICrudService<CustomerInfo> _customerInfo;
        public readonly ICrudService<CategoryInfo> _categoryInfo;
        public readonly IRawSqlRepository _rawSqlRepository;
        public readonly ICrudService<ProductInfo> _productInfo;

        public ReportController(UserManager<ApplicationUser> userManager, ICrudService<SupplierInfo> supplierInfo,
            ICrudService<CustomerInfo> customerInfo, IRawSqlRepository rawSqlRepository, ICrudService<CategoryInfo> categoryInfo,
            ICrudService<ProductInfo> productInfo)
        {
            _userManager = userManager;
            _supplierInfo = supplierInfo;
            _customerInfo = customerInfo;
            _rawSqlRepository = rawSqlRepository;
            _categoryInfo = categoryInfo;
            _productInfo = productInfo;
        }

        public async Task<IActionResult> Index(ReportViewModel reportViewModel)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId);
            ViewBag.supplierInfo = await _supplierInfo.GetAllAsync(p => p.IsActive == true && p.StoreInfoId == user.StoreId);
            ViewBag.customerInfo = await _customerInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);
           
            reportViewModel.search = new SearchCriteria();

           
            return View(reportViewModel);
        }

        public async Task<IActionResult> search(ReportViewModel reportViewModel)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId);
            ViewBag.supplierInfo = await _supplierInfo.GetAllAsync(p => p.IsActive == true && p.StoreInfoId == user.StoreId);
            ViewBag.customerInfo = await _customerInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);


            var customerId = reportViewModel.search.CustomerId.HasValue
                ? new SqlParameter("@CustomerId", SqlDbType.Int) { Value = reportViewModel.search.CustomerId }
                : new SqlParameter("@CustomerId", SqlDbType.Int) { Value = DBNull.Value };

            var PaymentMethodId = reportViewModel.search.PaymentMethod.HasValue
               ? new SqlParameter("@PaymentMethodId", SqlDbType.Int) { Value = reportViewModel.search.PaymentMethod }
               : new SqlParameter("@PaymentMethodId", SqlDbType.Int) { Value = DBNull.Value };

            var startDate = reportViewModel.search.StartDate.HasValue
               ? new SqlParameter("@startDate", SqlDbType.DateTime) { Value = reportViewModel.search.StartDate }
               : new SqlParameter("@startDate", SqlDbType.DateTime) { Value = DBNull.Value };

            var endDate = reportViewModel.search.EndDate.HasValue
          ? new SqlParameter("@endDate", SqlDbType.DateTime) { Value = reportViewModel.search.EndDate }
          : new SqlParameter("@endDate", SqlDbType.DateTime) { Value = DBNull.Value };

            var result = _rawSqlRepository.FromSql<CustomerReportViewModel>(
                "usp_GetTransactionInfo @CustomerId, @PaymentMethodId, @startDate, @endDate, @storeId",
                customerId, PaymentMethodId, startDate, endDate, new SqlParameter("@storeId", user.StoreId)).ToList();
                
            
            reportViewModel.customerReportViewModels = result;

            return View(nameof(Index), reportViewModel);
        }

        public async Task<IActionResult> DetailReport(ReportViewModel reportViewModel)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId);
            ViewBag.supplierInfo = await _supplierInfo.GetAllAsync(p => p.IsActive == true && p.StoreInfoId == user.StoreId);
            ViewBag.customerInfo = await _customerInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);
            ViewBag.categoryInfo = await _categoryInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);
            ViewBag.productInfo = await _productInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);


            reportViewModel.search = new SearchCriteria();


            return View(reportViewModel);
        }


        public async Task<IActionResult> SearchDetail(ReportViewModel reportViewModel)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId);
            ViewBag.supplierInfo = await _supplierInfo.GetAllAsync(p => p.IsActive == true && p.StoreInfoId == user.StoreId);
            ViewBag.customerInfo = await _customerInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);
            ViewBag.categoryInfo = await _categoryInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);
            ViewBag.productInfo = await _productInfo.GetAllAsync(p => p.StoreInfoId == user.StoreId);

            var customerId = reportViewModel.search.CustomerId.HasValue
                ? new SqlParameter("@CustomerId", SqlDbType.Int) { Value = reportViewModel.search.CustomerId }
                : new SqlParameter("@CustomerId", SqlDbType.Int) { Value = DBNull.Value };

            var supplierId = reportViewModel.search.SupplierId.HasValue
               ? new SqlParameter("@supplierId", SqlDbType.Int) { Value = reportViewModel.search.SupplierId }
               : new SqlParameter("@supplierId", SqlDbType.Int) { Value = DBNull.Value };

            var categoryId = reportViewModel.search.CategoryId.HasValue
               ? new SqlParameter("@categoryId", SqlDbType.Int) { Value = reportViewModel.search.CategoryId }
               : new SqlParameter("@categoryId", SqlDbType.Int) { Value = DBNull.Value };

            var productId = reportViewModel.search.ProductId.HasValue
               ? new SqlParameter("@productId", SqlDbType.Int) { Value = reportViewModel.search.ProductId }
               : new SqlParameter("@productId", SqlDbType.Int) { Value = DBNull.Value };

            var PaymentMethodId = reportViewModel.search.PaymentMethod.HasValue
               ? new SqlParameter("@PaymentMethodId", SqlDbType.Int) { Value = reportViewModel.search.PaymentMethod }
               : new SqlParameter("@PaymentMethodId", SqlDbType.Int) { Value = DBNull.Value };

            var startDate = reportViewModel.search.StartDate.HasValue
               ? new SqlParameter("@startDate", SqlDbType.DateTime) { Value = reportViewModel.search.StartDate }
               : new SqlParameter("@startDate", SqlDbType.DateTime) { Value = DBNull.Value };

            var endDate = reportViewModel.search.EndDate.HasValue
          ? new SqlParameter("@endDate", SqlDbType.DateTime) { Value = reportViewModel.search.EndDate }
          : new SqlParameter("@endDate", SqlDbType.DateTime) { Value = DBNull.Value };

            var result = _rawSqlRepository.FromSql<CustomerReportViewModel>(
                "usp_GetTransactionInfo @CustomerId, supplierId, @categoryId, @productId, @PaymentMethodId, @startDate, @endDate, @storeId",
                customerId, PaymentMethodId, startDate, endDate, new SqlParameter("@storeId", user.StoreId)).ToList();


            reportViewModel.customerReportViewModels = result;

            return View(nameof(Index), reportViewModel);
        }

    }
}

IMS.web/Controllers/UnitInfoController.cs
using IMS.infrastructure.IRepository;
using IMS.models.Entity;
using IMS.web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IMS.web.Controllers
{
    public class UnitInfoController : Controller
    {
        private readonly ICrudService<UnitInfo> _unitInfoService;
        private readonly UserManager<ApplicationUser> _userManager;

        public UnitInfoController(ICrudService<UnitInfo> unitInfoService, UserManager<ApplicationUser> userManager)
        {
            _unitInfoService = unitInfoService;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var unitInfoList = await _unitInfoService.GetAllAsync();
            return View(unitInfoList);
        }

        public async Task<IActionResult> AddEdit(int id)
        {

            UnitInfo unitInfo = new UnitInfo();
            unitInfo.IsActive = true;
            if (id > 0)
            {
                unitInfo = await _unitInfoService.GetAsync(id);
            }

            return View(unitInfo);
        }

        [HttpPost]

        public async Task<IActionResult> AddEdit(UnitInfo unitInfo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userId = _userManager.GetUserId(HttpContext.User);
                    if (unitInfo.Id == 0)
                    {
                        unitInfo.CreatedDate = DateTime.Now;
                        unitInfo.CreatedBy = userId;
                        await _unitInfoService.InsertAsync(unitInfo);

                        TempData["Success"] = "Unit Info Added Successfully";
                    }
                    else
                    {
                        var OrgUnitInfo = await _unitInfoService.GetAsync(unitInfo.Id);
                        OrgUnitInfo.UnitName = unitInfo.UnitName;
                        OrgUnitInfo.IsActive = unitInfo.IsActive;
                        OrgUnitInfo.ModifiedDate = DateTime.Now;
                        OrgUnitInfo.ModifiedBy = userId;
                        await _unitInfoService.UpdateAsync(OrgUnitInfo);

                        TempData["Success"] = "Unit Info Updated Successfully";
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["Error"] = "Error Occured While Adding/Updating Unit Info";
                    return RedirectToAction(nameof(AddEdit));
                }

            }
            TempData["Error"] = "Please Enter Valid Data";
            return RedirectToAction(nameof(AddEdit));

        }
    }


}

IMS.web/Views/Shared/Notification.cshtml
@if (TempData["success"] != null)
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" asp-append-version="true"/>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["success"]')
    </script>

}

@if (TempData["error"] != null)
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["error"]')
    </script>
}

IMS.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IMS</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IMS.web.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            padding-top: 56px; /* Adjust based on the navbar height */
        }

        .main-content {
            display: flex;
            flex: 1;
        }

        .sidebar {
            height: 100vh;
            width: 250px;
            position: fixed;
            top: 56px; /* Adjust based on the navbar height */
            left: 0;
            background-color: #A0E8CD;
            padding-top: 10px;
            overflow-y: auto;
            transition: width 0.3s;
        }

            .sidebar.hidden {
                width: 0;
                overflow: hidden;
            }

            .sidebar a {
                padding: 10px 15px;
                text-decoration: none;
                font-size: 18px;
                color: white;
                display: block;
            }

                .sidebar a:hover {
                    background-color: #D4F2EE;
                }

        .content {
            margin-left: 250px;
            padding: 20px;
            flex: 1;
            transition: margin-left 0.3s;
        }

            .content.expanded {
                margin-left: 0;
            }

        .navbar {
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
        }

        .sidebar .dropdown-menu {
            position: static;
            float: none;
            width: auto;
            margin-top: 0;
            border: none;
            border-radius: 0;
            box-shadow: none;
            transition: none;
            background-color: #A0E8CD;
            color: black;
        }

        #sidebarToggle {
            /* Reset all styles */
            border: none;
            background: none;
            padding: 0;
            margin: 0;
            color: inherit;
            font-size: inherit;
            cursor: pointer;
        }

            #sidebarToggle:focus {
                outline: none; /* Remove outline on focus */
            }


        .sidebar .dropdown-menu a {
            padding: 10px 20px; /* Adjust padding as needed */
        }

            .sidebar .dropdown-menu a:hover {
                background-color: #D4F2EE;
            }

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <button id="sidebarToggle" class="btn text-white"><i class="fas fa-bars"></i></button>
                <a class="navbar-brand mx-2" asp-area="" asp-controller="Dashboard" asp-action="Index">Inventory Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    @* <ul class="navbar-nav me-auto">
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("SUPERADMIN"))
                    {
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="StoreInfo" asp-action="Index">Store</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Index">User Settings</a>
                    </li>
                    }
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("ADMIN"))
                    {
                    <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Unit" asp-action="Index">Unit</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Rack" asp-action="Index">Rack</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Supplier" asp-action="Index">Supplier</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="ProductRate" asp-action="Index">Purchase</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Transaction" asp-action="Transaction">Transaction</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Report</a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="Index">Custom Report</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="DetailReport">Detail Report</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="Stock Report">Stock</a>
                    </div>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Index">Users Management</a>
                    </li>
                    }
                    </ul> *@
                    <ul class="navbar-nav me-auto">
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-content">
        <div class="sidebar">
            <ul class="navbar-nav">
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("SUPERADMIN"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="StoreInfo" asp-action="Index">Store</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">User Settings</a>
                    </li>
                }
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("ADMIN"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CategoryInfo" asp-action="Index">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="UnitInfo" asp-action="Index">Unit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="RackInfo" asp-action="Index">Rack</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="SupplierInfo" asp-action="Index">Supplier</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CustomerInfo" asp-action="Index">Customer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ProductInfo" asp-action="Index">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ProductRateInfo" asp-action="Index">Purchase Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TransactionInfo" asp-action="Transaction">Transaction</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Report</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Report" asp-action="Index">Custom Report</a>
                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Report" asp-action="DetailReport">Detail Report</a>
                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Report" asp-action="Stock">Stock</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Users Management</a>
                    </li>
                }
            </ul>
        </div>
        <div class="content">
            <main role="main" class="pb-3">
                <partial name="_Notification"></partial>
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.getElementById('sidebarToggle').addEventListener('click', function () {
            document.querySelector('.sidebar').classList.toggle('hidden');
            document.querySelector('.content').classList.toggle('expanded');
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IMS.web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" asp-append-version="true"/>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["success"]')
    </script>

}

@if (TempData["error"] != null)
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["error"]')
    </script>
}